### ISSUE TITLE
Bashbot crashes on '&&' parameters

### ISSUE THREAD

**Issue by mathew-fleisch** [mathew-fleisch/bashbot#39]
Sending '&&' on a valid bashbot trigger causes the whole binary to crash
```
time="2021-08-10T20:53:22Z" level=info msg="command detected: `bashbot ping &amp;&amp;`"
time="2021-08-10T20:53:22Z" level=info msg="Channel: GPFMM5MD2"
time="2021-08-10T20:53:22Z" level=info msg="User: UP3BBQX34"
time="2021-08-10T20:53:22Z" level=info msg="Timestamp: 1628628802.073200"
time="2021-08-10T20:53:22Z" level=info msg="0: bashbot"
time="2021-08-10T20:53:22Z" level=info msg="1: ping"
time="2021-08-10T20:53:22Z" level=info msg="2: &amp;&amp;"
time="2021-08-10T20:53:22Z" level=info msg="Send slack message[Channel:GPFMM5MD2]: :robot_face: Processing command..."
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.processWhitelistedCommand(0x40003a67c0, 0x1, 0x1, 0x400023a460, 0x9, 0x400052e5a0, 0x14, 0x400023a470, 0xc, 0x400023a46c, ...)
	/bashbot/cmd/bashbot/bashbot.go:410 +0x1a3c
main.processCommand(0x400042e000, 0x26b200)
	/bashbot/cmd/bashbot/bashbot.go:297 +0x8d8
main.handleMessage(0x400042e000)
	/bashbot/cmd/bashbot/bashbot.go:613 +0xc0
main.main()
	/bashbot/cmd/bashbot/bashbot.go:756 +0xbf8
```

**Comment by mathew-fleisch** [comment]
This only happens on command/triggers with no parameters as the slice/array is empty

**Comment by mathew-fleisch** [comment]
Once github-actions [status](https://www.githubstatus.com/) is back-up/green, the new tag should trigger a build and the new binaries/containers should not have this bug anymore

**Comment by mathew-fleisch** [comment]
https://github.com/mathew-fleisch/bashbot/releases/tag/v1.5.4 fixes this issue
